### ISSUE TITLE
[Feature Request] Read/write vault files

### ISSUE THREAD

**Issue by Migsi** [dseeley/ansible_vault_pipe#1]
Hello there!

First of all, thanks for providing this handy plugin! We were looking for something exactly like this as it would allow us to easily perform key rollovers within vaults using ansible itself. Though it looks like it is not (yet?) possible to directly read from/write to vault files directly. Do you already plan to extend the plugin to provide such feature? In any case, I can look forward to give you a hand with the implementation.

Best,
Migsi

**Comment by dseeley** [comment]
Hi - thanks for your interest in the plugin!

You can probably already do what you're looking for using the plugin as-is.  You would `slurp` your existing vaulted file, then `ansible_vault_pipe/decrypt`, then pass the decrypted variable to `ansible_vault_pipe/encrypt` (with a new password if desired), then `copy` the encrypted data back out (without attempting to decrypt):

```yaml
    - name: file slurp
      delegate_to: localhost
      slurp: src="vaulttest_vars.yml"
      register: r__slurp

    - name: ansible_vault_pipe decrypt
      ansible_vault_pipe:
        action: decrypt
        #vaultpass: "myexistingpassword"     #If not already loaded
        vaulttext: "{{ r__slurp.content | b64decode }}"
      register: r__ansible_vault_decrypt

    - name: ansible_vault_pipe encrypt
      ansible_vault_pipe:
        action: encrypt
        #vaultpass: "mynewpassword"     #If not already loaded or you want to change it
        multiline_out: yes
        plaintext: "{{ r__ansible_vault_decrypt.plaintext }}"
      register: r__ansible_vault_encrypt

    - name: copy file back out newly-encrypted
      delegate_to: localhost
      copy:
        content: "{{r__ansible_vault_encrypt.vaulttext}}"
        dest: "vaulttest_vars.yml"
        decrypt: no
```

[Note: I have just pushed a new version that adds the `multiline_out` option to the encrypt, so that this doesn't yield a very long single line of ciphertext.]
